Documentation:
    Enabled: false
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
